GET https://hangman-highscores-amif.onrender.com/scores
###
GET https://hangman-highscores-amif.onrender.com/scores/99
###
DELETE https://hangman-highscores-amif.onrender.com/scores/1
###
post http://apeura-server.onrender.com/scores
#Content-type: application/json

#{ "id": 10, "name": "maija" }
###
