GET https://apeura-server.onrender.com/scores
###
GET https://apeura-server.onrender.com/scores/99
###
DELETE https://apeura-server.onrender.com/scores/10
###
post http://apeura-server.onrender.com/scores
Content-type: application/json

{ "id": 10, "name": "maija" }
###
